# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{form_assistant}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Heath", "Chris Scharf"]
  s.date = %q{2012-07-06}
  s.description = %q{Custom form builder that attempts to make your forms friendly}
  s.email = %q{scharfie@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "autotest/testunit.rb",
    "form_assistant.gemspec",
    "forms/_check_box.html.erb",
    "forms/_field.html.erb",
    "forms/_fieldset.html.erb",
    "forms/_file_field.html.erb",
    "forms/_password_field.html.erb",
    "forms/_radio_button.html.erb",
    "forms/_text_area.html.erb",
    "forms/_text_field.html.erb",
    "init.rb",
    "install.rb",
    "lib/form_assistant.rb",
    "lib/form_assistant/error.rb",
    "lib/form_assistant/field_errors.rb",
    "lib/form_assistant/rules.rb",
    "tasks/form_assistant_tasks.rake",
    "test/forms/_field.html.erb",
    "test/forms/_fieldset.html.erb",
    "test/forms/_text_field.html.erb",
    "test/forms/_widget.html.erb",
    "test/helper.rb",
    "test/mock_rails.rb",
    "test/test_field_errors.rb",
    "test/test_form_assistant.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/scharfie/form_assistant}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Custom form builder that attempts to make your forms friendly}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<activesupport>, ["~> 2.3"])
      s.add_development_dependency(%q<actionpack>, ["~> 2.3"])
      s.add_development_dependency(%q<activerecord>, ["~> 2.3"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<activesupport>, ["~> 2.3"])
      s.add_dependency(%q<actionpack>, ["~> 2.3"])
      s.add_dependency(%q<activerecord>, ["~> 2.3"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<activesupport>, ["~> 2.3"])
    s.add_dependency(%q<actionpack>, ["~> 2.3"])
    s.add_dependency(%q<activerecord>, ["~> 2.3"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

